project:
  type: website

website:
  title: "data-viz"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - href: 001-syllabus.qmd
        text: Syllabus
      - href: 002-detailed-outline.qmd
        text: Details
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



